---
title: "IODS course project"
author: "InkaRonkainen"
output:
  prettydoc::html_pretty:
    theme: cayman
    toc: yes
    toc_depth: 2
    fig_caption: yes
    fig_width: 10
    fig_height: 8
  pdf_document:
    toc: yes
    toc_depth: '2'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(error = F, warning = F, message = F)
```

***

# **Introduction to Open Data Science - Course Project**

*This is my course diary where you can follow my learning journey.*

```{r child = "chapter1.Rmd"}
# This will include Chapter 1 (that is updated in its own file) in the document.
```
  
***
  
```{r child = "chapter2.Rmd"}
# This will include Chapter 2 (that is updated in its own file) in the document.
```

***

```{r child = "chapter3.Rmd"}
# This will include Chapter 3 (that is updated in its own file) in the document.
```

***
```{r child = "chapter4.Rmd"}
# This will include Chapter 4 (that is updated in its own file) in the document.
```

***
```{r child = "chapter5.Rmd"}
# This will include Chapter 5 (that is updated in its own file) in the document.
```

***
```{r child = "chapter6.Rmd"}
# This will include Chapter 5 (that is updated in its own file) in the document.
```

***